---
resources:
- name: pal-tracker
  type: git
  source:
    uri: https://github.com/vimal777/pal-tracker.git
    branch: master
    private_key: {{github-private-key}}

- name: deploy
  type: cf
  source:
    api: https://concourse.longs.pal.pivotal.io
    username: vsawant-pal
    password: 941ac123
    organization: capgemini
    space: sandbox

jobs:
- name: build-and-deploy
  plan:
  - get: pal-tracker
    trigger: true
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: deploy
    params:
      manifest: pal-tracker/manifest.yml
      path: build-output/pal-tracker.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from Concourse"